version: '3.8'

# Simplified Docker Compose for immediate deployment
# Focus on getting infrastructure and OpenWebUI running first

services:
  # Core Database - PostgreSQL with pgvector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: itp-postgres-simple
    environment:
      POSTGRES_DB: intelligent_teams_planner
      POSTGRES_USER: itp_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-itp_password_2024}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_simple_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U itp_user -d intelligent_teams_planner"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - itp-simple-network
    restart: unless-stopped

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: itp-redis-simple
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password_2024}
    volumes:
      - redis_simple_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - itp-simple-network
    restart: unless-stopped

  # Neo4j Knowledge Graph Database
  neo4j:
    image: neo4j:5.15-community
    container_name: itp-neo4j-simple
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-neo4j_password_2024}
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_simple_data:/data
      - neo4j_simple_logs:/logs
      - neo4j_simple_import:/var/lib/neo4j/import
      - neo4j_simple_plugins:/plugins
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7474/db/data/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - itp-simple-network

# OpenWebUI removed - using separate standalone container
# Container ID: f9cc2bf3b1e6fe9752c9d790d535ac25826eb0f13cf270af4f99709e08e93079

# Networks
networks:
  itp-simple-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

# Volumes
volumes:
  postgres_simple_data:
    driver: local
  redis_simple_data:
    driver: local
# openwebui_simple_data removed - using separate container
  neo4j_simple_data:
    driver: local
  neo4j_simple_logs:
    driver: local
  neo4j_simple_import:
    driver: local
  neo4j_simple_plugins:
    driver: local