version: '3.8'

# UV-Optimized Production Docker Compose for Intelligent Teams Planner v2.0
# 10-100x faster builds with UV package manager
# Usage: docker compose -f docker-compose.uv.yml up -d

services:
  # Core Database - PostgreSQL with pgvector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: itp-postgres-uv
    environment:
      POSTGRES_DB: intelligent_teams_planner
      POSTGRES_USER: itp_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-itp_password_2024}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_uv_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U itp_user -d intelligent_teams_planner"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - itp-uv-network
    restart: unless-stopped

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: itp-redis-uv
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password_2024}
    volumes:
      - redis_uv_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - itp-uv-network
    restart: unless-stopped

  # MCP Server - UV Optimized Build
  mcp-server:
    build:
      context: ./planner-mcp-server
      dockerfile: Dockerfile.uv
      cache_from:
        - python:3.11-slim
    container_name: itp-mcp-server-uv
    environment:
      - PORT=7100
      - DATABASE_URL=postgresql+asyncpg://itp_user:${POSTGRES_PASSWORD:-itp_password_2024}@postgres:5432/intelligent_teams_planner
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password_2024}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-12345678901234567890123456789012}
      - TESTING_MODE=false
      - LOG_LEVEL=INFO
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
    ports:
      - "7100:7100"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - itp-uv-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # MCPO Proxy - UV Optimized Build
  mcpo-proxy:
    build:
      context: ./mcpo-proxy
      dockerfile: Dockerfile.uv
      cache_from:
        - python:3.11-slim
    container_name: itp-mcpo-proxy-uv
    environment:
      - PORT=7105
      - MCP_SERVER_URL=http://mcp-server:7100
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password_2024}
      - LOG_LEVEL=INFO
    ports:
      - "7105:7105"
    depends_on:
      mcp-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7105/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - itp-uv-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M

  # Teams Bot - UV Optimized Build
  teams-bot:
    build:
      context: ./teams-bot
      dockerfile: Dockerfile.uv
      cache_from:
        - python:3.11-slim
    container_name: itp-teams-bot-uv
    environment:
      - PORT=7110
      - BOT_ID=${BOT_ID}
      - BOT_PASSWORD=${BOT_PASSWORD}
      - OPENWEBUI_URL=http://openwebui:7115
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password_2024}
      - LOG_LEVEL=INFO
    ports:
      - "7110:7110"
    depends_on:
      openwebui:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7110/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - itp-uv-network
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M

  # RAG Service - UV Optimized Build with ML Support
  rag-service:
    build:
      context: ./rag-service
      dockerfile: Dockerfile.uv
      cache_from:
        - python:3.11-slim
    container_name: itp-rag-service-uv
    environment:
      - DATABASE_URL=postgresql+asyncpg://itp_user:${POSTGRES_PASSWORD:-itp_password_2024}@postgres:5432/intelligent_teams_planner
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password_2024}
      - PORT=7120
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE_MB=100
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - OPENWEBUI_ENABLED=true
      - TEAMS_ENABLED=true
      - PLANNER_ENABLED=true
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
    volumes:
      - rag_uv_uploads:/app/uploads
      - rag_uv_cache:/app/cache
    ports:
      - "7120:7120"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7120/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - itp-uv-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Neo4j Knowledge Graph Database
  neo4j:
    image: neo4j:5.15-community
    container_name: itp-neo4j-uv
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-neo4j_password_2024}
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_uv_data:/data
      - neo4j_uv_logs:/logs
      - neo4j_uv_import:/var/lib/neo4j/import
      - neo4j_uv_plugins:/plugins
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7474/db/data/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - itp-uv-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # OpenWebUI - Central Conversational Hub
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: itp-openwebui-uv
    environment:
      - OPENAI_API_BASE_URL=http://mcpo-proxy:7105/v1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy-key}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-your-secret-key}
      - ENV=production
      - LOG_LEVEL=INFO
    volumes:
      - openwebui_uv_data:/app/backend/data
    ports:
      - "7115:8080"
    restart: unless-stopped
    depends_on:
      mcpo-proxy:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - itp-uv-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

# Networks
networks:
  itp-uv-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

# Volumes
volumes:
  postgres_uv_data:
    driver: local
  redis_uv_data:
    driver: local
  openwebui_uv_data:
    driver: local
  neo4j_uv_data:
    driver: local
  neo4j_uv_logs:
    driver: local
  neo4j_uv_import:
    driver: local
  neo4j_uv_plugins:
    driver: local
  rag_uv_uploads:
    driver: local
  rag_uv_cache:
    driver: local