[tool.poetry]
name = "intelligent-teams-planner"
version = "0.1.0"
description = ""
authors = ["Master_CCOMGROUP <160778939+ccomcorp@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
