[tool.poetry]
name = "teams-bot"
version = "2.0.0"
description = "Microsoft Teams Bot for Intelligent Teams Planner"
authors = ["Intelligent Teams Planner Team <team@example.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
botbuilder-core = "^4.15.0"
botbuilder-schema = "^4.15.0"
botbuilder-integration-aiohttp = "^4.15.0"
botbuilder-adapters-slack = "^4.15.0"
aiohttp = "^3.9.0"
aiohttp-cors = "^0.7.0"
redis = {extras = ["hiredis"], version = "^5.0.0"}
httpx = {extras = ["http2"], version = "^0.25.0"}
pydantic = "^2.5.0"
pydantic-settings = "^2.1.0"
python-dotenv = "^1.0.0"
structlog = "^23.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.11.0"
black = "^23.9.0"
isort = "^5.12.0"
flake8 = "^6.1.0"
mypy = "^1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]